### PR TITLE
Fix profile cnf issues

### PR DESCRIPTION
**Pull request by warunalakshitha**

### CODE REVIEW

**Comment by rasika** [comment]
Is this still reproducible?

**Comment by yanyuxiyangzk** [comment]
I also have this same problem.
When i cd IOT_HOME which is in product-iots-3.1.0-M7 catalog, then i run mvn clean install ,it happened a error .like this

[INFO] WSO2 IoT - Parent .................................. SUCCESS [  0.812 s]
[INFO] WSO2 IoT - Components Module ....................... SUCCESS [  0.109 s]
[INFO] WSO2 IoT - UI Styles ............................... SUCCESS [  1.248 s]
[INFO] WSO2 IoT - Features Module ......................... SUCCESS [  0.080 s]
[INFO] WSO2 IoT - Styles Feature .......................... SUCCESS [  0.905 s]
[INFO] WSO2 IoT - Scripts ................................. SUCCESS [  0.078 s]
[INFO] WSO2 IoT - QSG Script .............................. SUCCESS [  3.946 s]
[INFO] WSO2 IoT - Tools ................................... SUCCESS [  0.071 s]
[INFO] WSO2 IoT - Device Type Archetype ................... SUCCESS [  1.521 s]
[INFO] WSO2 IoT - P2 Profile Module ....................... SUCCESS [  0.069 s]
[INFO] WSO2 IoT - Core P2 Profile Gen ..................... FAILURE [02:04 min]
[INFO] WSO2 IoT - Analytics P2 Profile Gen ................ SKIPPED
[INFO] WSO2 IoT - Broker P2 Profile Gen ................... SKIPPED
[INFO] WSO2 IoT - Distribution ............................ SKIPPED
[INFO] WSO2 IoT - Integration Module ...................... SKIPPED
[INFO] WSO2 IoT - Integration Test Common ................. SKIPPED
[INFO] WSO2 IoT - Integration Common ...................... SKIPPED
[INFO] WSO2 IoT - Integration Test Common Web UI Pages .... SKIPPED
[INFO] WSO2 IOT - Integration Test Module ................. SKIPPED
[INFO] WSO2 IoT - Integration Test UI Module .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2017-05-15T10:33:09+08:00
[INFO] Final Memory: 48M/520M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-
gen (3-p2-profile-generation) on project wso2iot-core-p2-profile: P2 publisher r
eturn code was 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :wso2iot-core-p2-profile

**Comment by rasika** [comment]
@yanyuxiyangzk Can you create an issue with the full error log you getting. Did you get the latest updates through a `git pull` ?

**Comment by charithag** [comment]
Closing this PR as this is no longer valid with latest product structure.

**Pull request closed without merging**
